### ISSUE TITLE
Download sources in zip file (enhancement request)

### ISSUE THREAD

**Issue by subiron** [neva-dev/felix-search-webconsole-plugin#1]
Idea is to generate zip package with source files.
e.g.
1. Select checkboxes near bundlers you want to decompile
2. Click download az ZIP

**Comment by pun-ky** [comment]
very nice feature request, thank you. I will try to implement it in feature. Hard to estimate when, but max in a month I think.

You could also implement it by your own then PR appreciated.

**Comment by krystianpanek** [comment]
fixed in release 1.1.0

**Comment by pun-ky** [comment]
released in 1.1.0
