### ISSUE TITLE
Error starting 

### ISSUE THREAD

**Issue by Neo110** [neva-dev/felix-search-webconsole-plugin#11]
ERROR: Bundle com.neva.felix.webconsole.plugins.search [7] Error starting file:/Users/zhengbin/Documents/applications/felix-framework-5.6.4/search-webconsole-plugin-1.1.1-SNAPSHOT.jar (org.osgi.framework.BundleException: Unable to resolve com.neva.felix.webconsole.plugins.search [7](R 7.0): missing requirement [com.neva.felix.webconsole.plugins.search [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.5.0)(!(version>=2.0.0))) Unresolved requirements: [[com.neva.felix.webconsole.plugins.search [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.5.0)(!(version>=2.0.0)))])
org.osgi.framework.BundleException: Unable to resolve com.neva.felix.webconsole.plugins.search [7](R 7.0): missing requirement [com.neva.felix.webconsole.plugins.search [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.5.0)(!(version>=2.0.0))) Unresolved requirements: [[com.neva.felix.webconsole.plugins.search [7](R 7.0)] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.5.0)(!(version>=2.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4133)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2118)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1372)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pun-ky** [comment]
most recent version of felix? hmmm missing org.slf4j in version 1.5.0 up to 2.0; maybe try to add that missing bundle on instance? I will try to encapsulate / remove that dependency to make plugin even more universal... but I need to find time for it, maybe next week.

Regards

**Comment by pun-ky** [comment]
closing as no further communication
