### ISSUE TITLE
Replace decompiler with Fernflower

### ISSUE THREAD

**Issue by pun-ky** [neva-dev/felix-search-webconsole-plugin#13]
https://github.com/JetBrains/intellij-community/tree/master/plugins/java-decompiler/engine

**Comment by pun-ky** [comment]
or https://mvnrepository.com/artifact/org.benf/cfr/0.146

**Comment by ielali** [comment]
Hello since we've moved to Java 11 the bundle stopped working because of the compiler compatibility. Following your suggestion in the ticket I switched the compiler locally to cfr and it's working alright. If you're interested I can submit a pull request. (I was blocked from ding so)

**Comment by pun-ky** [comment]
Sure. If it works 🙂 then I will release next version with that fix.

**Comment by krystian-panek-vmltech** [comment]
thanks @ielali , finally released 2.0.0; sorry for lag ;)
