### ISSUE TITLE
Show line numbers

### ISSUE THREAD

**Issue by gruberrolandvaltech** [neva-dev/felix-search-webconsole-plugin#16]
Thanks a lot for this great tool. :)

It would be great if you could display the line numbers when showing a decompiled class.

**Comment by pun-ky** [comment]
It is not trivial. Usually the line numbers from exception stack trace are not matching the line numbers in decompiled class so that I am intentionally not showing it. However decompiler could be improved / in detail be replaced by that one used by IntelliJ which better decompiles classes in case of matching origin class source line numbers. Still PR is appreciated 😉 in other words, covered by #13

**Comment by paul-bjorkstrand** [comment]
While still not trivial, it isn't as complex as requiring a different decompilation library. You could use the output from a decompilation to match the outputted source to the original source (as listed in the line number table in the compiled class.

You would start by not using [`Decompilter.decompile`](https://bitbucket.org/mstrobel/procyon/src/7f403952ba5a0aed13479bdc08566a613e798fcd/Procyon.CompilerTools/src/main/java/com/strobel/decompiler/Decompiler.java#lines-29). Instead, copy most of the code there (thank you Apache License) into your [`OsgiExplorer.decompileClass`](https://github.com/neva-dev/felix-search-webconsole-plugin/blob/develop/src/main/java/com/neva/felix/webconsole/plugins/search/core/OsgiExplorer.java#L156). Then, use the output of [`Language.decompileType`](https://bitbucket.org/mstrobel/procyon/src/7f403952ba5a0aed13479bdc08566a613e798fcd/Procyon.CompilerTools/src/main/java/com/strobel/decompiler/languages/Language.java#lines-41) (called [here](https://bitbucket.org/mstrobel/procyon/src/7f403952ba5a0aed13479bdc08566a613e798fcd/Procyon.CompilerTools/src/main/java/com/strobel/decompiler/Decompiler.java#lines-70), which returns a [`TypeDecompilationResults`](https://bitbucket.org/mstrobel/procyon/src/7f403952ba5a0aed13479bdc08566a613e798fcd/Procyon.CompilerTools/src/main/java/com/strobel/decompiler/languages/TypeDecompilationResults.java). That result type contains a list of [`LineNumberPosition`](https://bitbucket.org/mstrobel/procyon/src/default/Procyon.CompilerTools/src/main/java/com/strobel/decompiler/languages/LineNumberPosition.java), which can be used to match line numbers in the outputted source, with the original line numbers from the decompiled class.

Again, I am not trying to trivialize it, just giving some information for anyone who has the time to dig in, develop it, and test it.

**Comment by pun-ky** [comment]
@paul-bjorkstrand thanks for nice analysis, as you stated

> anyone who has the time to dig in, develop it, and test it.

looking for such awesome person :)

**Comment by krystian-panek-vmltech** [comment]
2.0.0 has sth like that:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/81212505/218435752-0fff0a1a-da9a-45cc-9598-80d8b35d87a7.png">
