### ISSUE TITLE
run_prettify.js is not available

### ISSUE THREAD

**Issue by bencebarna** [neva-dev/felix-search-webconsole-plugin#29]
https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js is not available anymore. It has been deprecated a while back: https://groups.google.com/g/js-code-prettifier/c/IFHev_kLm30. We possible need to replace the [url](https://github.com/neva-dev/felix-search-webconsole-plugin/blob/e4236aa18aba9c8461bfb35a02bd21509ae672dc/src/main/resources/search/common.html#L3) with https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js

**Comment by krystian-panek-vmltech** [comment]
or maybe better we should embed the script ;)

**Comment by krystian-panek-vmltech** [comment]
fixed and released in https://github.com/neva-dev/felix-search-webconsole-plugin/releases/tag/2.0.2

thanks @bencebarna for reporting
