### ISSUE TITLE
Adding 'Search' button instead of typeahead

### ISSUE THREAD

**Issue by magdu** [neva-dev/felix-search-webconsole-plugin#8]
IMHO it would be more user friendly if button "Search" will be addded.
Now the search is starting when search field lost focus and every time we change something in filters. 
It would be easier to set filters to desired options and then run search. As it is now, we generate unnecessery search queries in beetween...

**Comment by pun-ky** [comment]
Of course It was in the meantime implemented, but most often you don't know what you are looking for... so when results are displayed immediately (performance is good enough), it is a chance, that you will see what we looking for more quickly.

Let's vote, from me: -1
